# version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/basta_db
      - DEBUG=1
      - REDIRECT_URI=https://api.intra.42.fr/oauth/authorize?client_id=u-s4t2ud-132fa5622bce53a46a8bed31d7e99019853b85977cc5fece17d95b9ee8cdff22&redirect_uri=https%3A%2F%2Flocalhost%3A8000%2Fprofile&response_type=code
    networks:
      - basta-network
    entrypoint: ["/bin/bash", "/app/scripts/entrypoint.sh"]

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=basta_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - basta-network

volumes:
  postgres_data:

networks:
  basta-network:
    driver: bridge