# Generated by Django 5.0.7 on 2024-12-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_rename_completed_match_is_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score_player1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_player2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
