# Generated by Django 5.0.7 on 2025-01-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_match_score_player1_match_score_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('tournament', 'nickname')},
        ),
    ]
