# Generated by Django 4.2.30 on 2026-08-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameapp", "0002_tictactoequeue_tictactoematch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tictactoequeue",
            name="user",
        ),
        migrations.DeleteModel(
            name="TicTacToeMatch",
        ),
        migrations.DeleteModel(
            name="TicTacToeQueue",
        ),
    ]
