# Generated by Django 4.2.19 on 2025-02-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0003_user_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
