# Generated by Django 4.2.19 on 2025-03-06 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0004_alter_user_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[("PONG", "Pong"), ("TICTACTOE", "TicTacToe")],
                        max_length=10,
                    ),
                ),
                ("opponent", models.CharField(max_length=150)),
                (
                    "result",
                    models.CharField(
                        choices=[("WIN", "Win"), ("LOSS", "Loss"), ("DRAW", "Draw")],
                        max_length=4,
                    ),
                ),
                ("score", models.CharField(max_length=10)),
                ("date_played", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Match Histories",
                "ordering": ["-date_played"],
            },
        ),
    ]
